thymeleaf:
    cache: false
    prefix: classpath:/templates/    # 設定去templates資料夾找html檔案
    suffix: .html
    encoding: UTF-8
    mode: HTML5
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huiyutang
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  
#   prod
#    url: jdbc:mysql://10.31.192.3/huiyutang?cloudSqlInstance=huiyutang:asia-east1:hui-yu-tang&socketFactory=com.google
#    .cloud.sql.mysql.SocketFactory&user=web_service&password=~\\e*6{1?Xj/7r2x
#    username: web_service
#    password: ~\\e*6{1?Xj/7r2x
#    driver-class-name: com.google.cloud.sql.mysql.SocketFactory
#    driver-class-name: com.mysql.cj.jdbc.Driver  
  security:
    encrypt:
      key: ThisIsASecretKey 
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
   

jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
